services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - auth-next-trpc_default

volumes:
  postgres-db:
  redis:
  pgadmin:

networks:
  auth-next-trpc_default:
    external: true
