services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - auth-next-trpc_default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: 'redis/redis-stack:latest'
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    env_file:
      - ./.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis:/data
    depends_on:
      - next-app

  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - auth-next-trpc_default

volumes:
  postgres-db:
  redis:
  pgadmin:

networks:
  auth-next-trpc_default:
    external: true
